name = "new-web-updated-7"
compatibility_date = "2025-01-01"

pages_build_output_dir = "livingroom507/public"

# Environment variables for the Pages Functions
[vars]
ADMIN_API_KEY = "TEST-KEY-123"
DO_WORKER_URL = "https://livingroom507-do-final-worker.roblq123.workers.dev"

# This section tells your Pages Functions where to find the database called 'DB'
[[d1_databases]]
binding = "DB"
database_name = "livingroom507-db"
migrations_dir = "db/migrations"  # <--- ADD THIS LINE
database_id = "67c24ec3-b2ff-4831-bd97-f5249339ee14" # You MUST replace this with your actual D1 ID

# Root wrangler.toml

[[durable_objects.bindings]]
name = "COLLAB_ROOM"
class_name = "CollaborationRoom"
script_name = "livingroom507-do-final-worker"