name = "livingroom507newupdate-7"
main = "workers/collaboration-room.js"
compatibility_date = "2025-01-01"

[[durable_objects.bindings]]
name = "COLLAB_ROOM"
class_name = "CollaborationRoom"

[[d1_databases]]
binding = "DB"
database_name = "livingroom507-db"