name = "livingroom507newupdate-7"
main = "workers/collaboration-room.js"
compatibility_date = "2025-01-01"

[[durable_objects.bindings]]
name = "COLLAB_ROOM"
class_name = "CollaborationRoom"

[[migrations]]
tag = "v1"
new_classes = [ "CollaborationRoom" ]

[[d1_databases]]
binding = "DB"
database_name = "livingroom507-db"
database_id = "67c24ec3-b2ff-4831-bd97-f5249339ee14" # <--- IMPORTANT: Replace with your actual D1 Database ID